development:
  secret_key_base: 3a000abd7538bb06e2bfd1b18eebe19cccdd217de54448ebb2e96c250101dbe1527f218902c676b4a6e7cbf91c826b2315495230cd5de76f6e90aecab76dcda7
  
test:
  secret_key_base: 3a000abd7538bb06e2bfd1b18eebe19cccdd217de54448ebb2e96c250101dbe1527f218902c676b4a6e7cbf91c826b2315495230cd5de76f6e90aecab76dcda7y

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>